version: '3'

services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: i20213tn001
      MYSQL_DATABASE: cines
      MYSQL_USER: cines
      MYSQL_PASSWORD: i20213tn001
    ports:
      - "3004:3306"
  
  cinepolis:
    build:
      context: ./cinepolis
      dockerfile: Dockerfile
    ports:
      - "8001:80" 
      
  cinemex:
    build:
      context: ./cinemex
      dockerfile: Dockerfile
    ports:
      - "8002:80" 
