version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.1
    environment:
      MYSQL_ROOT_PASSWORD: i20213tn001
      MYSQL_DATABASE: cines
      MYSQL_USER: cines
      MYSQL_PASSWORD: i20213tn001
  
  cinepolis:
    build:
      context: ./examenU2/cinepolis
      dockerfile: Dockerfile
    ports:
      - "8001:80" 
    networks:
      - app-network
      
  cinemex:
    build:
      context: ./examenU2/cinemex
      dockerfile: Dockerfile
    ports:
      - "8002:80" 
    networks:
      - app-network    

networks:
  app-network:
    driver: bridge
