version: '3.8'

services:
  mysql-db:
    image: mysql:8.0.1
    environment:
      MYSQL_ROOT_PASSWORD: i20213tn001
      MYSQL_DATABASE: cines
      MYSQL_USER: cines
      MYSQL_PASSWORD: i20213tn001
  
  frontend:
    build:
      context: ./examenU2 
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
